# Generated by Django 3.1.4 on 2020-12-16 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='docanalyzer/')),
                ('uploader_ip', models.GenericIPAddressField(null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FileMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_length', models.DecimalField(decimal_places=2, max_digits=18)),
                ('longest_words', models.JSONField()),
                ('number_palindromes', models.IntegerField()),
                ('number_unique_words', models.IntegerField()),
                ('number_words', models.IntegerField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docanalyzer.fileupload')),
            ],
        ),
    ]
