# Generated by Django 3.1.4 on 2020-12-16 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docanalyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemetric',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='docanalyzer.fileupload'),
        ),
    ]
